Update @shopify/react-html to public version
Shopify/unite-react-node-app-workshop pull request #15
Opened 2018-10-04 17:44 UTC by ismail-syed

We are in the process of deprecating @shopify/react-html from our PackageCloud registry as it's causing many issues. This PR upgrades the package to the latest 1.0.x public version. 

I did a tiny 🎩 but running `npm start`. I don't think anything broke, but might be worth another tophat.

2018-10-09 14:44 UTC, marutypes requested changes
https://github.com/Shopify/unite-react-node-app-workshop/blob/step5/server/render-react-app.js#L9 all the steps that actually use server rendering will likely break from this change, as we renamed `deferedScripts` to `scripts`.

2018-10-09 14:58 UTC, ismail-syed commented
Looking at the [`package-lock.json`](https://github.com/Shopify/unite-react-node-app-workshop/blob/master/package-lock.json#L45-L48), this repo is using the public version, `1.0.2`. Is that correct @TheMallen, haven't work with `package-lock.json` much.  If so, we can close this PR.

2018-10-10 18:06 UTC, ismail-syed commented
@TheMallen, I've updated this PR to pin the version to 1.0.2. The lock file resolves to that version

2018-10-15 14:15 UTC, marutypes approved these changes

2018-10-15 14:16 UTC, merged